#
# Dockerfile for building nginx images
# 
# https://github.com/v3u3i87/upadd-docker.git
#

FROM mysql:5.7
MAINTAINER Richard.Zhang <v3u3i87@gmail.com>

ENV TZ "Asia/Shanghai"

# COPY config/my.cnf /etc/mysql/my.cnf